---
title: "Control tissue PCA"
author: "Eli Roberson"
date: "May 02, 2024"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r libraries}
library( here )
library( tidyverse )
```

```{r results_make}
dir.create( path = here( 'results', 'figures' ), 
            showWarnings = FALSE, 
            recursive = TRUE )
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	fig.path = paste0( here( 'results', 'figures' ), "/" ),
	fig.keep = 'all',
	dpi = 300
)
```

```{r source}
source( file = here( 'src', 'shared_functions.R' ) )
```

```{r info}
info <- read_tsv( file = here( 'info', 'project_info.tsv' ) ) %>%
  filter( status == "Control" )
```

```{r read_windows_rlog}
rlog <- read_csv( file = here( 'results', 
                               'control_only_tissue_rlog.csv.gz' ) )
```

```{r ids}
gene_num <- 50

tissue_id <- read_csv( 
  file = here( 'results',
               'control_only_plasma_vs_urine_deg.csv.gz' ) ) %>%
  slice_min( order_by = qval, n = gene_num ) %>%
  pull( gene_id )
```

```{r pca_calc}
pca_out <- rlog %>%
  filter( gene_id %in% tissue_id ) %>%
  as.data.frame( . ) %>%
  column_to_rownames( 'gene_id' ) %>%
  as.matrix( . ) %>%
  t( . ) %>%
  prcomp( x = ., scale. = FALSE )

percent_variance <- round( pca_out$sdev^2 / sum( pca_out$sdev^2 )* 100.0, 2 )
```

```{r add_info}
pca_plot_input <- pca_out$x %>%
  as.data.frame( . ) %>%
  rownames_to_column( 'rgsm' ) %>%
  merge( ., info, by = 'rgsm' )
```

```{r cluster}
# Add clusters
clusters <- pca_plot_input %>%
  select( ., PC1, PC2 ) %>%
	kmeans( x = ., centers = 2 )

pca_plot_input$cluster_num <- clusters$cluster
pca_plot_input$cluster <- LETTERS[ clusters$cluster ]
```

```{r tissue_pca}
first_plot_pc <- 1
second_plot_pc <- 2

x_dim_name <- paste0( "PC", 
                      first_plot_pc, 
                      " (", 
                      percent_variance[ first_plot_pc ], 
                      "%)" )

y_dim_name <- paste0( "PC", 
                      second_plot_pc, 
                      " (", 
                      percent_variance[ second_plot_pc ], 
                      "%)" )

# important note
# OK look - for some reason the initial generation code gave reversed PC1 axes.
# If you want the pure PC output, set flip PC1 to false

flip_pc_1 = TRUE

if ( flip_pc_1 ) { 
  flip_factor = -1.0
} else {
  flip_factor = 1.0
}

pca_plot <- ggplot( data = pca_plot_input, 
                    mapping = aes( flip_factor * PC1, 
                                   PC2, 
                                   shape = tissue, 
                                   colour = tissue ) ) +
  theme_bw() +
  scale_color_manual( values = colorBlindPalette ) +
  geom_point( size = 5 ) +
  gg_bigger_texts +
  gg_center_title +
  xlab( x_dim_name ) +
  ylab( y_dim_name ) +
  theme( legend.position = 'top' )

pca_plot
```

```{r highlighted_pca}
pca_plot +
  geom_rect( aes( ymin = -8, 
                  ymax = 7, 
                  xmin = -17, 
                  xmax = 8 ), 
             fill = "lightblue", 
             alpha=0.7, 
             inherit.aes = FALSE ) +
  geom_rect( aes( ymin = -2, 
                  ymax = 3, 
                  xmin = 10.5, 
                  xmax = 19 ), 
             fill = "lightgreen", 
             alpha=0.7, 
             inherit.aes = FALSE ) +
  geom_point( size = 5, colour = 'black' )
```

```{r versions}
Sys.time()
getwd()
sessionInfo()
```
