---
title: "All sample rlog deg"
author: "Eli Roberson"
date: "May 03, 2024"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r libraries}
library( here )
library( tidyverse )
library( DESeq2 )
```

```{r results_make}
dir.create( path = here( 'results', 'figures' ), 
            showWarnings = FALSE, 
            recursive = TRUE )
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	fig.path = paste0( here( 'results', 'figures' ), "/" ),
	fig.keep = 'all',
	dpi = 300
)
```

```{r annotation}
annotation <- read_tsv( file = here( 'info', 
                                     'gene_transcript_name_maps.tsv.gz' ) ) %>%
  select( `Ensembl Gene ID`, `Associated Gene Name` ) %>%
  dplyr::rename( gene_id = `Ensembl Gene ID` ) %>%
  dplyr::rename( symbol = `Associated Gene Name` ) %>%
  distinct( . )
```

```{r info}
info <- read_tsv( file = here( 'info', 'project_info.tsv' ) ) %>%
  mutate( mod_status = paste0( status, "_", tissue ) ) %>%
  as.data.frame( . )
rownames( info ) = info$rgsm
```

```{r read_genes}
data_mat <- read_tsv ( file = here( 'data',
                                   'exosome_counts.tsv.gz' ), 
                      col_types = cols( .default = col_integer(), 
                                        gene_id = col_character() ) ) %>%
  as.data.frame( . ) %>%
  column_to_rownames( var = 'gene_id' ) %>%
  as.matrix( . )
```

```{r filter}
keep_sample_ids <- intersect( x = info$rgsm, 
                              y = colnames( data_mat ) )

info <- info[ keep_sample_ids, ]

data_mat <- data_mat[ , keep_sample_ids ]

deseq_design_matrix <- info[ , c( "run_batch", "mod_status" ), drop = FALSE ]
```

```{r overall_counts}
col_counts <- colSums( x = data_mat, na.rm = TRUE )

col_counts

# TOTAL READS
sum( col_counts )
```

```{r deseq2}
deseqObj <- DESeqDataSetFromMatrix( countData = data_mat, 
                                    colData = deseq_design_matrix, 
                                    design = ~ run_batch + mod_status )

deseqObj <- DESeq( deseqObj,
                   test="Wald",
                   betaPrior=FALSE )
```

```{r diff_exp_genes_urine}
results <- results( 
  object = deseqObj, contrast = c( 'mod_status', 
                                   'SLE_plasma_exosomes', 
                                   'Control_plasma_exosomes' ) )  %>%
	as.data.frame( . ) %>%
	rownames_to_column( "gene_id" ) %>%
  filter( !is.na( log2FoldChange ) ) %>%
  filter( !is.na( pvalue )  ) %>%
  filter( !is.na( padj ) ) %>%
  left_join( y = annotation, 
             by = 'gene_id' ) %>%
	mutate( log2FC = log2FoldChange ) %>%
	mutate( FC = 2^log2FC ) %>%
	mutate( FC = case_when( 
		FC < 1.0 ~ -1 / FC,
		TRUE ~ FC )
	) %>%
	mutate( pval = pvalue ) %>%
	mutate( qval = padj ) %>%
	select( gene_id, symbol, FC, log2FC, pval, qval ) %>%
	arrange( qval, pval ) %>%
  write_csv( path = here( 'results', 
                          'LN_over_Control_plasma_gene_DEG_updated.csv.gz' ) )
```

```{r extracting_logrratio}
assay( rlog( object = deseqObj,
             blind=FALSE ) ) %>%
  	as.data.frame( . ) %>%
  	rownames_to_column( "gene_id" ) %>%
  	write_csv( path =  
  	             here( 'results', 
  	                   'control_lupus_plasma_urine_gene_rlog.csv.gz' ) ) 
```

```{r versions}
Sys.time()
getwd()
sessionInfo()
```
